POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "werty",
    "email": "lkjuio@example.com",
    "address": "qwemain street",
    "dateofBirth":"1998-09-09",
    "registeredDate":"2021-11-18"

}