POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "John Doe with billing account45",
    "email": "rrtyuio@example.com",
    "address": "123 main street",
    "dateofBirth":"1999-09-09",
    "registeredDate":"2025-11-18"

}