POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "yashyk",
    "email": "yashyk@example.com",
    "address": "1234 main street",
    "dateofBirth":"1998-09-09",
    "registeredDate":"2021-11-18"

}