PUT http://localhost:4000/patients/1675bc5d-1b02-4e3f-a342-75c92287d3cf
Content-Type: application/json

{
  "name": "parth dalvi",
  "email": "pd@gmail.com",
  "address": "01233456 main street",
  "dateofBirth":"1999-09-09"

}